import type { Metadata } from "next";
import Provider from '../../components/provider';
import "./globals.css";

export const metadata: Metadata = {
  title: "MAX is PAUL",
  description: "Generated by PAUL",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
