import type { Metadata } from "next";
import "./globals.css";
import Layout from "../../components/layout";



export const metadata: Metadata = {
  title: "MAX is PAUL",
  description: "Generated by PAUL",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Layout >
      <body>{children}</body>
      </Layout>
    </>
  );
}
