import Head from "next/head";
import "./globals.css";
import Layout from "../../components/layout";


export const metadata = {
  title: "MAX IS PAUL portfolio",
  description: "Generated by PAUL",
};

export default function RootLayout({ children }) {
  return (
    <Layout>
      <body>{children}</body>
    </Layout>
  );
}
