import type { Metadata } from "next";
import "./globals.css";
import Header from "../../components/header";
import Footer from "../../components/footer";

export const metadata: Metadata = {
  title: "MAX is PAUL",
  description: "Generated by PAUL",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
          {children}
      </body>
    </html>
  );
}
